### ISSUE TITLE
Revoking MS Tokens

### ISSUE THREAD

**Issue by benrobson** [dommilosz/minecraft-auth#10]
Let me know if you need more detail...
Just looking for a method where on logout you can revoke the MS Account/Session or if the user logs in with the wrong account, or if there's an error with logging in, I can revoke the session/token.

**Comment by dommilosz** [comment]
You cannot revoke access token but can revoke refresh token. Also if you want to revoke only Minecraft session I think it would be easy to implement too. 
Source: https://docs.microsoft.com/en-us/answers/questions/672062/how-to-revoke-token.html

**Comment by dommilosz** [comment]
I can't really find anything useful. This link above is for graph ql which from my testing is not for revoking this kind of tokens. I think it's safe to simply forget about the token and if user really wants to remove it he can go to authorised applications and remove it

**Comment by dommilosz** [comment]
Most of the unofficial minecraft launchers have no option to remove the app in the launcher itself.

**Comment by benrobson** [comment]
So is there a way to effectively "logout" of the session without having to have the user clear their cache?

**Comment by dommilosz** [comment]
I think user has to remove the app in his Microsoft account to revoke the tokens.

**Comment by james090500** [comment]
I know this is a very old issue, but you I can comment a fix so it can be closed. 

If you add `&prompt=select_account` to the end of the URL the user will always be prompted to choose which Microsoft account they want to log into, useful if they have multiple.

**Comment by dommilosz** [comment]
I don't think it's what the OP meant but I'll implement that in next version
