### ISSUE TITLE
Is it possible to get the access token for cracked or am i doing it wrong?

### ISSUE THREAD

**Issue by jdknowstocode** [dommilosz/minecraft-auth#14]
Hi there, im trying to login using the cracked authentication and can't seem to get the accessToken. Here is my code
```javascript
    const authmc = window.require('minecraft-auth') 
    async function test () {
        let account = new authmc.CrackedAccount("ViolaterZ");

        console.log(account)
    }
```

Please do reply soon, Thanks.

**Comment by dommilosz** [comment]
For cracked account the access token should be null. It's no possible to obtain it. Minecraft has no problem with running with null access token

**Comment by jedidiahp** [comment]
oh but i am getting this error while launching
![image](https://user-images.githubusercontent.com/73651672/206435551-e7140766-cef8-4e4e-af06-8fa7c9164ec2.png)
any solutions you can think of?

**Comment by jedidiahp** [comment]
version of what exactly? the minecraft version or something else?

**Comment by jedidiahp** [comment]
it doesn't work

**Comment by dommilosz** [comment]
How do you launch minecraft? Did you add --version 1.19.2 or smth and when doing --accessToken it puts null there?

**Comment by jedidiahp** [comment]
yes it does but still says that it is required

**Comment by dommilosz** [comment]
How do you launch Minecraft I need some code that causes that issue.

**Comment by dommilosz** [comment]
Do you need any more help? If not please close the issue.

**Comment by jdknowstocode** [comment]
nope, i found a way around it - thanks
