### ISSUE TITLE
Can i get a working example for this library

### ISSUE THREAD

**Issue by VertixSexyDev** [dommilosz/minecraft-auth#16]

**Comment by dommilosz** [comment]
What example do you need? What doesn't work for you what you want to achieve and what you tried?

**Comment by VertixSexyDev** [comment]
can i get a example of how to get the account accessToken as i couldnt figure out how to get the accessToken from the url, i allow access to my acccount but it only gives me refresh token, but i want the accessToken

**Comment by VertixSexyDev** [comment]
never mind i figured it out thanks
