### ISSUE TITLE
Disable or use custom function for logs

### ISSUE THREAD

**Issue by CordonZeus22** [dommilosz/minecraft-auth#20]
Would it be possible to add an option for disable the logs or use a custom function to be used instead of the `console.log` ?

Also, would it be possible to add a log when the MS Token Server is close ?

**Comment by dommilosz** [comment]
You know when the server closes either by catching exception or successfully getting the code so you can implement your own logging in that case.

**Comment by CordonZeus22** [comment]
I'm ok with that, but if an `onstart` callback is added, why don't add an `onclose` callback ? I think it's more logic than awaiting the result for knowing the state of the server cause it can be handled with the `close` event of the server. For the code you send, the log isn't in the `createServer` function and called by the callback of the `listen` method ?

**Comment by dommilosz** [comment]
Take a look on #21. I've added onstart, onclose and oncode callbacks

**Comment by CordonZeus22** [comment]
For `onstart` callback, why don't use the callback of the `listen` method like before ? For `onclose` callback, I thought use the `close` event from the server. I have pushed that on my fork if you want to check
