### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by LemonJuicer96** [dommilosz/minecraft-auth#3]
Do I need to refresh tokens myself or does the package do it for me?

**Comment by dommilosz** [comment]
If you use account.use() it will automatically refresh the token if needed

**Comment by dommilosz** [comment]
Here is code fragment that does it:
```
async use() {
        if (await this.checkValidToken()) {
            return this.accessToken;
        } else {
            if (this.login_username && this.login_password) {
                try {
                    await this.refresh();
                    return this.accessToken;
                } catch (e) {
                    await this.Login();
                    return this.accessToken;
                }
            } else {
                await this.refresh();
                return this.accessToken;
            }
        }
    }
```
If the token is valid it returns it
If the token is invalid it will first refresh it. Than if it fails login with account credentials.

I see that I check if the account has credentials even if it only tries to refresh it (only client token and old access token needed). I will fix soon :)

**Comment by dommilosz** [comment]
If you have any questions/suggestions feel free to ask.
