### ISSUE TITLE
Public clients can't send a client secret.

### ISSUE THREAD

**Issue by oRafael07** [dommilosz/minecraft-auth#31]
I can't authenticate.

my code:
![image](https://github.com/user-attachments/assets/d2d3e858-b5b2-4517-be69-12d775ef039c)

terminal result:
![image](https://github.com/user-attachments/assets/89fd5234-30be-48ff-8e9d-3a89a943efd0)

**Comment by dommilosz** [comment]
Which type of app did you create in Azure? Note that public client apps can't have app secrets. 

For more reference look up [wiki](https://github.com/dommilosz/minecraft-auth/wiki/How-to-setup-Microsoft-Auth)

**Comment by oRafael07** [comment]
I tried through the Web setup in [wiki](https://github.com/dommilosz/minecraft-auth/wiki/How-to-setup-Microsoft-Auth)

now i have another error

code:
![image](https://github.com/user-attachments/assets/6c3491ce-fe09-46f6-9d68-7d0eff3b26f0)

terminal result:
![image](https://github.com/user-attachments/assets/41eb718e-0caa-498d-ab2e-4af747f0b230)

**Comment by dommilosz** [comment]
You need to be approved by Microsoft to use your own app unfortunately, follow the link you got in your error message

**Comment by dommilosz** [comment]
You have form to fill out and then wait some time but they'll most likely approve it

**Comment by oRafael07** [comment]
Where can I find this form?

**Comment by dommilosz** [comment]
The link in the error message redirects to post about it and there is form link there

aka.ms/appreginfo
And the form link: aka.ms/mce-reviewappid

**Comment by oRafael07** [comment]
ok, thanks!
