### ISSUE TITLE
Token refresh invalid_grant error

### ISSUE THREAD

**Issue by Zmito26dev** [dommilosz/minecraft-auth#32]
Hello, I am using this line of code to refresh the access token.

`const accessToken = await storedAccount.use();`

It works correctly, but now that the token has expired I am getting the following error:

`invalid_grant: The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. The token was issued for a different client id`

I have temporarily solved it by changing the default appID of the package with my own (I guess I will have to do a fork to solve this), the thing is that I am receiving yet another error:

`invalid_grant: The user could not be authenticated as the grant is expired. The user must sign in again.`

I guess I'm doing something wrong but I don't know what, my idea is that the user only has to log in once and not constantly.

**Comment by dommilosz** [comment]
Which architecture you're using? Public client or web app? Send minimal example that reproduces that error.

**Comment by Zmito26dev** [comment]
I was using public client like this:
```js
const MicrosoftAuth = minecraftAuth.MicrosoftAuth;
let account = new minecraftAuth.MicrosoftAccount();
const accountStorage = new minecraftAuth.AccountsStorage();

async function logIn() {
  MicrosoftAuth.setup({appID:"my-appID", selectAccount:true});
  let pkce = MicrosoftAuth.generatePKCEPair();
  let code = await MicrosoftAuth.listenForCode({pkcePair:pkce});

  if (code !== undefined) {
    await account.authFlow(code, pkce);
    accountStorage.addAccount(account);
    const accountData = accountStorage.serialize();
    localStorage.setItem('minecraftAccount', accountData);
  }
}
  ```
Now I have changed it to a web app (to see if that solves it) like this:
```js
const MicrosoftAuth = minecraftAuth.MicrosoftAuth;
let account = new minecraftAuth.MicrosoftAccount();
const accountStorage = new minecraftAuth.AccountsStorage();

async function logIn() {
  MicrosoftAuth.setup({appID:"my-appID", appSecret:"secret", selectAccount:true});
  let code = await MicrosoftAuth.listenForCode();

  if (code !== undefined) {
    await account.authFlow(code);
    accountStorage.addAccount(account);
    const accountData = accountStorage.serialize();
    localStorage.setItem('minecraftAccount', accountData);
  }
}
 ``` 
When launching Minecraft I execute the following code:
  ```js
const loadedData = localStorage.getItem("minecraftAccount")
const loadedStorage = minecraftAuth.AccountsStorage.deserialize(loadedData);

const storedAccount = loadedStorage.getAccount(0);
const accessToken = await storedAccount.use();

const authorization = {
  access_token: accessToken,
  uuid: storedAccount.uuid,
  name: storedAccount.username,
}
  ```
It works correctly but when it came to refreshing the token it gave an error. Maybe now with the web app mode it will be solved.

**Comment by dommilosz** [comment]
Do you generate your account using the same client id as you're using to refresh it? Based on this error `invalid_grant: The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. The token was issued for a different client id` it looks like you have mismatch between client that created that account in the first place and client that tries to refresh it.

**Comment by Zmito26dev** [comment]
Yes, at first I got that error since the library uses the appID that comes by default when refreshing the token. I solved it by temporarily modifying the library and changing the default appID to mine with which I created the account.

The thing is that now I was also getting the following error:
`invalid_grant: The user could not be authenticated as the grant is expired. The user must sign in again.`

I will wait until tomorrow for the token to expire and see if using the web app mode does not give this error.

**Comment by dommilosz** [comment]
Public client grants have lifetime of 24h after that user must sign in again. The web app with the app secret shouldn't have this issue.

**Comment by Zmito26dev** [comment]
Perfect, thank you very much! 😊

**Comment by dommilosz** [comment]
But I'm wondering why didn't my builtin appid work
